apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-navigator-lite.fullname" . }}
  labels:
    {{- include "uptime-navigator-lite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "uptime-navigator-lite.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
